baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Nextjs Craftcms D3js Concept Cms'
primary: true
siteGroup: 9853d061-103f-4fe2-a5e1-3d976d508a41 # Nextjs Craftcms D3js Concept Cms
sortOrder: 1
