columnSuffix: null
contentColumnType: string
fieldGroup: d30a435b-5c95-4459-81c6-68f731b1f3bf # Common
handle: businessesPriorities
instructions: ''
name: 'Businesses Priorities'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:11728963-0164-41d6-ad01-3620456fc284' # Business Probabilities
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
