dateModified: 1637598550
email:
  fromEmail: carter@camelcasecollective.com
  fromName: 'Nextjs Craftcms D3js Concept Cms'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2d4fc014-2d57-41f6-9d7a-06a257aeb468: Default # Default
    70ce1490-e9fc-48d6-9267-c58ccc034f00: 'Businesses Priorities' # Businesses Priorities
    707c649a-3b3f-449f-94db-37f13562a50d: Homepage # Homepage
    9853d061-103f-4fe2-a5e1-3d976d508a41: 'Nextjs Craftcms D3js Concept Cms' # Nextjs Craftcms D3js Concept Cms
    11728963-0164-41d6-ad01-3620456fc284: 'Business Probabilities' # Business Probabilities
    99775712-aca5-4683-8f0a-bc48c95a3f88: Probability # Probability
    a0730db8-e428-4108-a9ea-cb66af011139: 'Public Schema' # Public Schema
    a50a94d6-bbca-445d-b746-7274f165e417: Homepage # Homepage
    d1b19cff-ec8a-4e0a-a2fd-879f63410bb7: 'Nextjs Craftcms D3js Concept Cms' # Nextjs Craftcms D3js Concept Cms
    d30a435b-5c95-4459-81c6-68f731b1f3bf: Common # Common
    e3eb4ae6-2a1d-4edd-b31d-c45cb92b4af6: Headline # Headline
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Nextjs Craftcms D3js Concept Cms'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
